---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: debug-statements
          - id: name-tests-test
          - id: requirements-txt-fixer
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.0
      hooks:
          - id: mypy
            additional_dependencies: [types-pyyaml, types-requests]
            exclude: ^testing/resources/
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
      rev: v0.5.5
      hooks:
      # Run the linter.
          - id: ruff
            args: [--fix]
      # Run the formatter.
          - id: ruff-format
